Added the blacklisting of a peer
catalyst-network/Protocol pull request #33
Opened 2019-05-23 08:41 UTC by Millymanz

Added the blacklisting of a peer

2019-05-23 09:35 UTC, franssl commented on src/Rpc.proto
> +	bool blacklist = 3;
```suggestion
bool blacklist = 3;
```

2019-05-23 10:08 UTC, monsieurleberre requested changes
see suggestions

2019-05-23 10:08 UTC, monsieurleberre commented on src/Rpc.proto
> +message GetPeerBlackListRequest {
As discussed, this name is a bit more accurate if you want to change the peer's status
```suggestion
message UpdatePeerBlackListRequest {
```

2019-05-23 10:08 UTC, monsieurleberre commented on src/Rpc.proto
> +message GetPeerBlackListResponse{
```suggestion
message UpdatePeerBlackListResponse{
```

2019-05-23 10:09 UTC, monsieurleberre submitted a review, later dismissed
OK for me

2019-05-23 11:39 UTC, monsieurleberre approved these changes

2019-05-24 13:34 UTC, monsieurleberre approved these changes

2019-05-24 13:45 UTC, nshCore approved these changes

2019-05-24 13:45 UTC, merged