add docs and sdk modules
catalyst-network/Protocol pull request #75
Opened 2019-09-07 13:10 UTC by nshCore

2019-09-09 11:31 UTC, monsieurleberre reviewed
the indexes are off sometimes I think

2019-09-09 11:31 UTC, monsieurleberre commented on src/Transaction.proto
> +    uint64 Amount = 3; // 8 byte amount
why 3 ?

2019-09-09 11:31 UTC, monsieurleberre commented on src/Transaction.proto
>      EntryRangeProof EntryRangeProofs = 3;
why not 4?

2019-09-09 13:03 UTC, monsieurleberre reviewed
OK on principle but I don't understand why the submodules are here, and not the other way round:
each SDK should be using files from this project, but this project seems to intend to push files in the SDK projects 🤔
Also I wouldn't check in the submodules as they don't appear to work on the CI or individual machines

2019-09-09 14:15 UTC, monsieurleberre submitted a review, later dismissed
OK maybe get the Peer changed too as this is a massively breaking change to get better types in anyway?

2019-09-09 14:15 UTC, monsieurleberre commented on src/Peer.proto
> +message PeerId {
Should we sort this one out too?

2019-09-09 14:43 UTC, franssl commented on src/Cryptography.proto
> +    bytes PublicKey = 1;
```suggestion
    bytes PrivateKey = 1;
```

2019-09-09 15:00 UTC, monsieurleberre commented on src/Cryptography.proto
> +    bytes PublicKey = 1;
I have it changed to `Bytes` locally :)

2019-09-09 15:02 UTC, monsieurleberre commented on src/Deltas.proto
>  message CandidateDeltaBroadcast {
Considering what happened to TransactionBroadcast, shouldn't these ones go to the "Wire" file
?

2019-09-09 15:21 UTC, monsieurleberre requested changes
let's make sure we use the correct types :/

2019-09-09 15:21 UTC, monsieurleberre commented on src/Account.proto
> +    bytes Address = 3;
Maybe rename to HashedBytes or Hash, or something more meaningful?

2019-09-09 15:21 UTC, monsieurleberre commented on src/Transaction.proto
> +    sint64 TransactionFees = 3; // 8 bytes, clear text, fees * 10^12 - always positive
should be uint64 given the comment
```suggestion
    uint64 TransactionFees = 3; // 8 bytes, clear text, fees * 10^12
```

2019-09-09 15:21 UTC, monsieurleberre commented on src/Transaction.proto
> +    sint64 TransactionFees = 4; // 8 bytes, clear text, fees * 10^12 - always positive
```suggestion
    uint64 TransactionFees = 4; // 8 bytes, clear text, fees * 10^12
```

2019-09-09 15:21 UTC, monsieurleberre commented on src/Transaction.proto
> +    sint64 TransactionFees = 4; // 8 bytes, clear text, fees * 10^12 - always positive
```suggestion
    uint64 TransactionFees = 4; // 8 bytes, clear text, fees * 10^12
```

2019-09-09 15:21 UTC, monsieurleberre commented on src/Transaction.proto
> +    sint64 Amount = 2; // max 8 bytes (always positive).
```suggestion
    uint64 Amount = 2; // max 8 bytes
```

2019-09-09 15:41 UTC, monsieurleberre submitted a review, later dismissed
OK better now I think

2019-09-09 15:50 UTC, monsieurleberre commented on src/Transaction.proto
> +	NORMAL = 0; // Public transaction type.
the AccountType and SignatureType use the words `Confidential` and `Public`, I think here too we should go for that rather than `Normal`

2019-09-09 16:01 UTC, monsieurleberre commented on src/Transaction.proto
> +message CFTransactionEntry {
ConfidentialTxEntry ?

2019-09-09 16:01 UTC, monsieurleberre commented on src/Transaction.proto
>  message STTransactionEntry {
PublicTxEntry?

2019-09-11 14:47 UTC, atlassanjay commented on src/Cryptography.proto
> +message PublicKey {
A key wrapping a byte string makes the structure kinda weird

2019-09-11 14:48 UTC, atlassanjay commented on src/Cryptography.proto
> +message PrivateKey {
When do we even need this in a proto object?

2019-09-11 14:59 UTC, atlassanjay commented on src/Peer.proto
> +    int32 reputation = 2; // reputation of peer
Please use sint32
Check the proto docs:
https://developers.google.com/protocol-buffers/docs/proto

```
Uses variable-length encoding. Inefficient for encoding negative numbers – if your field is likely to have negative values, use sint32 instead.
--
```

2019-09-11 15:00 UTC, atlassanjay commented on src/Transaction.proto
> +    sint64 amount = 2; // 8 byte amount
uint64

2019-09-11 15:02 UTC, atlassanjay commented on src/Transaction.proto
> +    uint64 amount = 2; // 8 byte amount
uint64 OR EVM uses uint256 (might want to use bytes)

2019-09-11 15:04 UTC, JayArrowz reviewed
Looks better, just need to address the comments

2019-09-13 10:28 UTC, monsieurleberre commented on src/Transaction.proto
> +    sint64 Amount = 2; // max 8 bytes
??
```suggestion
    uint64 Amount = 2; // max 8 bytes
```

2019-09-17 11:40 UTC, merged

2019-09-17 11:40 UTC, monsieurleberre commented
Catalyst.Node code adapted to these changes in https://github.com/catalyst-network/Catalyst.Node/pulls